### ISSUE TITLE
请问找不到指定的路径怎么办

### ISSUE THREAD

**Issue by zyzkun** [Montaro2017/bili_novel_packer#22]
PathNotFoundException: Cannot create file, path = '普通攻击是全体二连击，这样的妈妈你喜欢吗 \普通攻击是全体二连击，这样 的妈妈你喜欢吗 .epub' (OS Error: 系统找不到指定的路径。
, errno = 3)
#0      _File.throwIfError (dart:io/file_impl.dart:675)
#1      _File.createSync (dart:io/file_impl.dart:306)
#2      new OutputFileStream (package:archive/src/io/output_file_stream.dart:29)
#3      ZipFileEncoder.create (package:archive/src/io/zip_file_encoder.dart:65)
#4      EpubPacker.pack (package:bili_novel_packer/epub_packer/epub_packer.dart:170)
#5      NovelPacker._combineVolume (package:bili_novel_packer/novel_packer.dart:133)
<asynchronous suspension>
#6      NovelPacker.pack (package:bili_novel_packer/novel_packer.dart:82)
<asynchronous suspension>
#7      start (file:///d:/projects/bili_novel_packer/bin/main.dart:38)
<asynchronous suspension>
#8      main (file:///d:/projects/bili_novel_packer/bin/main.dart:14)
<asynchronous suspension>

代码小白不会搞,爹帮帮我罢

**Comment by zyzkun** [comment]
我是SB
