### ISSUE TITLE
部分小说无法读取，输入就崩溃

### ISSUE THREAD

**Issue by ai30328348** [Montaro2017/bili_novel_packer#37]
部分小说无法读取，按理说应该可以实现吧，隔壁wenku8-downloader支持下载轻小说文库站点已下架的小说。
希望增加功能
```
欢迎使用轻小说打包器!
作者: Spark
当前版本: 0.2.18
如遇报错请先查看能否正常访问输入网址
否则请至开源地址携带报错信息进行反馈: https://gitee.com/Montaro2017/bili_novel_packer
请输入URL(支持哔哩轻小说&轻小说文库):
https://www.wenku8.net/book/3.htm
正在加载数据...
RangeError (length): Invalid value: Not in inclusive range 0..3: 5
#0      WenkuNovelSource.getNovel (package:bili_novel_packer/light_novel/wenku_novel/wenku_novel_source.dart)
<asynchronous suspension>
#1      NovelPacker.init (package:bili_novel_packer/novel_packer.dart:48)
<asynchronous suspension>
#2      start (file:///d:/workdir/bili_novel_packer/bin/main.dart:35)
<asynchronous suspension>
#3      main (file:///d:/workdir/bili_novel_packer/bin/main.dart:14)
<asynchronous suspension>

运行出错，按回车键退出.(0.2.18)
```

**Comment by Montaro2017** [comment]
不支持下载已下架小说

**Comment by ai30328348** [comment]
这个可不是下架的小说

```
欢迎使用轻小说打包器!
作者: Spark
当前版本: 0.2.18
如遇报错请先查看能否正常访问输入网址
否则请至开源地址携带报错信息进行反馈: https://gitee.com/Montaro2017/bili_novel_packer
请输入URL(支持哔哩轻小说&轻小说文库):
https://www.wenku8.net/book/2118.htm
正在加载数据...

书名: 带着智慧型手机闯荡异世界
作者: 冬原パトラ
状态: 连载中
标签: [穿越, 魔法, 战斗, 龙傲天, 后宫]
　　手拿智慧型手机，在异世界展开的温馨冒险故事！
　　因为神明的失误而死去的望月冬夜，在异世界开启了第二人生。他拥有被神明提高能力的身体，以及在异世界也能使用的智慧型手机。他发挥着善良的天性，与许多人们相遇，结识重要挚友。
　　在经历这些过程的途中，主角在不知不觉间得知这个世界的秘密。他继承了古代文明的遗产、跟乐天的世界之王们携手合作，悠哉地环游着世界——

[1] 第一卷
[2] 第二卷
[3] 第三卷
[4] 第四卷
[5] 第五卷
[6] 第六卷
[7] 第七卷
[8] 第八卷
[9] 第九卷
[10] 第十卷
[11] 第十一卷
[12] 第十二卷
[13] 第十三卷
[14] 第十四卷
[15] 第十五卷
[16] 第十六卷
[17] 第十七卷
[18] 第十八卷
[19] 第十九卷
[20] 第二十卷
[21] 第二十一卷
[22] 第二十二卷
[23] 第二十三卷
[24] 第二十四卷
[25] 第二十五卷
[26] 第二十六卷
[27] 第二十七卷
[28] 第二十八卷
[29] 第二十九卷
---------------
[0] 选择全部
请选择需要下载的分卷(可输入如1-9进行范围选择以及如2,5单独选择):9

[1] 是
[2] 否
是否在每章开头添加章节标题? 1

[注意]: 轻小说文库设置了速率限制，不能请求过快，因此打包速度较慢，请耐心等待.

开始打包 第九卷...
FormatException: Bad GBK encoding 0x8068
#0      _GbkStreamDecoder.convert (package:fast_gbk/src/gbk.dart:380)
#1      GbkDecoder.convert (package:fast_gbk/src/gbk.dart:228)
#2      GbkCodec.decode (package:fast_gbk/src/gbk.dart:61)
#3      HttpUtil.getStringFromGbk.<anonymous closure> (package:bili_novel_packer/util/http_util.dart:59)
<asynchronous suspension>
#4      WenkuNovelSource._getNovelChapter.<anonymous closure> (package:bili_novel_packer/light_novel/wenku_novel/wenku_novel_source.dart:135)
<asynchronous suspension>
#5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33)
<asynchronous suspension>
#6      WenkuNovelSource._getNovelChapter (package:bili_novel_packer/light_novel/wenku_novel/wenku_novel_source.dart:132)
<asynchronous suspension>
#7      RetryOptions.retry (package:retry/retry.dart:131)
<asynchronous suspension>
#8      NovelPacker._resolveChapter (package:bili_novel_packer/novel_packer.dart:143)
<asynchronous suspension>
#9      Future.wait.<anonymous closure> (dart:async/future.dart:525)
<asynchronous suspension>
#10     NovelPacker._packVolume (package:bili_novel_packer/novel_packer.dart:220)
<asynchronous suspension>
#11     NovelPacker.pack (package:bili_novel_packer/novel_packer.dart:76)
<asynchronous suspension>
#12     start (file:///d:/workdir/bili_novel_packer/bin/main.dart:38)
<asynchronous suspension>
#13     main (file:///d:/workdir/bili_novel_packer/bin/main.dart:14)
<asynchronous suspension>

运行出错，按回车键退出.(0.2.18)
```

**Comment by Montaro2017** [comment]
用bilinovel代替 
https://www.bilinovel.com/novel/2271.html
