### ISSUE TITLE
[BUG] 无法正常使用

### ISSUE THREAD

**Issue by BeBetterWang** [Montaro2017/bili_novel_packer#50]
### 使用版本
使用版本:  0.2.25

### 复现步骤

1. 输入网址：https://www.linovelib.com/novel/9.html
2. 选择分卷：全部
3. 错误信息：错误信息截图
![image](https://github.com/user-attachments/assets/e682dbfd-b03f-4146-a4cb-776c11e64f9e)

如果闪退请使用CMD执行exe文件重复闪退操作，最后可以看到错误信息
[bili_novel.log](https://github.com/user-attachments/files/17686573/bili_novel.log)

**Comment by Montaro2017** [comment]
#49

**Comment by Montaro2017** [comment]
你能用反而是个奇怪的问题
#49

**Comment by Leonoves** [comment]
楼主解决了吗 我的也是这样

**Comment by BeBetterWang** [comment]
> 楼主解决了吗 我的也是这样

木有啊。。。

**Comment by XMZO** [comment]
```
Null check operator used on a null value
#0      WenkuNovelSource._getNovelChapter (package:bili_novel_packer/light_novel/wenku_novel/wenku_novel_source.dart:149)
<asynchronous suspension>
#1      RetryOptions.retry (package:retry/retry.dart:131)
<asynchronous suspension>
#2      NovelPacker._resolveChapter (package:bili_novel_packer/novel_packer.dart:155)
<asynchronous suspension>
#3      Future.wait.<anonymous closure> (dart:async/future.dart:534)
<asynchronous suspension>
#4      NovelPacker._packVolume (package:bili_novel_packer/novel_packer.dart:208)
<asynchronous suspension>
#5      NovelPacker.pack (package:bili_novel_packer/novel_packer.dart:76)
<asynchronous suspension>
#6      start (file:///d:/myprojects/bili_novel_packer/bin/main.dart:44)
<asynchronous suspension>
#7      main (file:///d:/myprojects/bili_novel_packer/bin/main.dart:15)
<asynchronous suspension>
```


轻小说文库同样报错
